name: great_awareness_frontend
description: Psychology insights app frontend
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  device_info_plus: ^10.1.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  table_calendar: ^3.0.9
  provider: ^6.1.1
  vocsy_epub_viewer: ^2.0.0
  path_provider: ^2.1.1
  flutter_inappwebview: ^5.8.0
  url_launcher: ^6.1.14
  video_player: ^2.8.1
  chewie: ^1.7.0
  flutter_cache_manager: ^3.3.1
  xml: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/