name = "gwa-wellness-worker"
main = "worker.js"
compatibility_date = "2024-12-29"

# The new Wellness Database
[[d1_databases]]
binding = "WELLNESS_DB"
database_name = "gwa-wellness-db"
database_id = "ea3f72c4-ff64-4ba0-a6e1-f52f0d489ccb"

# The existing Users Database (Read-only access usually sufficient, but binding gives full access)
[[d1_databases]]
binding = "USERS_DB"
database_name = "gwa-main-db"
database_id = "71bfffe9-e765-4929-94ce-f71187ab0214"

# The new Milestone Database
[[d1_databases]]
binding = "MILESTONE_DB"
database_name = "milestone"
database_id = "2ab787d4-8441-436a-a7e4-61b0807b0bc7"

# The Events Database
[[d1_databases]]
binding = "EVENTS_DB"
database_name = "events"
database_id = "f943d1f3-1865-4aab-9649-77a1b425e79f"
