name = "gwa-wellness-worker"
main = "worker.js"
compatibility_date = "2024-12-29"

# The new Wellness Database
[[d1_databases]]
binding = "WELLNESS_DB"
database_name = "gwa-wellness-db"
database_id = "ea3f72c4-ff64-4ba0-a6e1-f52f0d489ccb"

# The existing Users Database (Read-only access usually sufficient, but binding gives full access)
[[d1_databases]]
binding = "USERS_DB"
database_name = "gwa-main-db"
database_id = "71bfffe9-e765-4929-94ce-f71187ab0214"
